### ISSUE TITLE
[BUG] No Models Indexed

### ISSUE THREAD

**Issue by adrianpaiva1** [matchish/laravel-scout-elasticsearch#147]
**Describe the bug**
No models are indexed when running php artisan scout:import. Console does not display anything

**To Reproduce**

Include a custom Searchable Trait which uses the Scout Searchable Trait
run php artisan scout:import

**Expected behavior**
Should index models

**Additional context**
Only happens on v4.0.4

**Version**
v4.0.4
Laravel 8
scout 8.5

This is the trait included in all of my models

![image](https://user-images.githubusercontent.com/19557611/102675001-de2e2300-4165-11eb-94db-c7a6a62c1b5f.png)

**Comment by matchish** [comment]
@ametad Any thoughts?

**Comment by ametad** [comment]
What PHP version?

**Comment by ametad** [comment]
I am enjoying my holidays now and I need some free time 😄 . So I am looking at this again after 3 januari. Hope you'll understand!

**Comment by adrianpaiva1** [comment]
PHP Version 7.4

**Comment by ametad** [comment]
Here is the logic of determining if the trait is included:

https://github.com/matchish/laravel-scout-elasticsearch/blob/84b65da1cc26f0ead6046a346b92a7f19d94fca4/src/Searchable/SearchableListFactory.php#L147

It does not yet recognizes traits that are included from within traits. That's the problem here I think.

**Comment by ametad** [comment]
@matchish I am thinking more and more that the old way perhaps is the best way after all. The convenience of not loading the classes maybe not outweigh all trouble in making it work in all scenarios. What do you think? 

This was my original problem: #135 

I can overcome my problem also with explicitly import the classes by name, like so:

`artisan scout:import App\\Model`

**Comment by matchish** [comment]
We can rollback to previous solution for now  reopen #135. And maybe later we'll find more simple solution. Also you can wrap scout:import command to your own command and use the solution you implemented already that cover your needs, and pass finded classes explicitly to command from this package.

**Comment by matchish** [comment]
And of course no need to do it right now. So enjoy your vacation)

**Comment by matchish** [comment]
So if someone have the issue please use 4.0.2 for now

**Comment by ametad** [comment]
> We can rollback to previous solution for now, and reopen #135. And maybe later we'll find more simple solution. Also you can wrap scout:import command to your own command and use the solution you implemented already that cover your needs, and pass finded classes explicitly to command from this package.

I am wondering, am I they only one with the problem described in #135? Or otherwise the need finding classes without loading them? 

Turning back the changes is fine by me. I thought it would make life easier to be able to use `scout:import` without arguments to index all searchable models to Elasticsearch. But it is quite a challenge so far... I don't think it makes life easier, anymore 🤣 

@matchish What are your thoughts?

**Comment by matchish** [comment]
We are not alone) https://github.com/algolia/scout-extended/issues/213

**Comment by ametad** [comment]
Fixed in 4.0.5

https://github.com/matchish/laravel-scout-elasticsearch/pull/152

**Comment by matchish** [comment]
@adrianpaiva1  Feel free to reopen if you still have the issue after update to 4.0.5
