### ISSUE TITLE
[BUG] No results with empty search term

### ISSUE THREAD

**Issue by krio-rogue** [matchish/laravel-scout-elasticsearch#233]
**Describe the bug**
No results with empty search term

**To Reproduce**
```
$query = Products::search('car');
$result = $query->paginate(5);
echo 'Count : ' . $result->count() . "\n"; //=> 'Count : 5'
echo 'Total : ' . $result->total() . "\n"; //=> 'Count : 8'

$query = Products::search('');
$result = $query->paginate(5);
echo 'Count : ' . $result->count() . "\n"; //=> 'Count : 0'
echo 'Total : ' . $result->total() . "\n"; //=> 'Count : 0'
```

**Expected behavior**
Return not empty collection 

**Additional context**
`class SearchFactory` on method `create` add `QueryStringQuery` without check on empty `$builder->query`

**Version**
laravel/framework:v9.50.2
laravel/scout:v9.8.0
matchish/laravel-scout-elasticsearch:v7.0.0
`docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" elasticsearch:8.6.1
`

**Comment by matchish** [comment]
It's a feature of Elasticsearch https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_whitespaces_and_empty_queries

**Comment by krio-rogue** [comment]
Thanks for the answer.

Yes, it's a feature of Elasticsearch, but other scout engine return document with empty query string (test algolia, meilisearch, database).
Perhaps the documentation for the scout package should describe the desired behavior for search engines.

Found some solutions. Using '*' as default value for string or add to callback function next code
```php
if (empty($body['query']['query_string']['query'])) {
    unset($body['query']['query_string']['query']);
}
if (empty($body['query']['query_string'])) {
    unset($body['query']['query_string']);
}
if (empty($body['query'])) {
    unset($body['query']);
}
```

**Comment by matchish** [comment]
Thanks for the workaround. But I think that compatibility can't be achieved for all cases. 
For example Products::search('title:Barcelona or to:Barcelona') I don't think that all other engines support this semantic.
Even with basic query we can't expect the same results Products::search('Barcelona') because results depends a lot of mappings analysers filters.
I understand that Products::search('') is most basic query but to be honest even with this example I think it's better to stick to elastic behaviour
If you want to have the same results I think you have to implement abstractions on queries

Here an example of pseudocode what I mean
```
interface Query {
  toString()
}
class Elasticsearch/AllItemsQuery implements Query
class MelliSearch/AllItemsQuery implements Query
Product::search($query->toString())
```
