### ISSUE TITLE
[BUG] NoNodeAvailableException: No alive nodes. All the 1 nodes seem to be down

### ISSUE THREAD

**Issue by hazratmilad** [matchish/laravel-scout-elasticsearch#246]
**Describe the bug**

node is alive and i can access by curl :
curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic https://localhost:9200

but with api call :

NoNodeAvailableException: No alive nodes. All the 1 nodes seem to be down. in file /var/www/html/vendor/elastic/transport/src/NodePool/SimpleNodePool.php on line 77

**Additional context**

SCOUT_DRIVER=Matchish\ScoutElasticSearch\Engines\ElasticSearchEngine
ELASTICSEARCH_HOST=https://localhost:9200
ELASTICSEARCH_USER=elastic
ELASTICSEARCH_PASSWORD=O8loD2Uvy4-XDL-CIl2P

**Version**

Versions of Laravel 10, Scout 10, and the package 7.2.1.

**Comment by matchish** [comment]
The package use official elasticsearch client https://github.com/matchish/laravel-scout-elasticsearch/blob/5d83dd7dbcbaa77d13246a73014d930ef3144625/src/ElasticSearchServiceProvider.php#L24
I believe if you will instantiate the client by yourself you'll get the same error. Usually people have the issue because of wrong configuration

**Comment by kbiro-nander** [comment]
@hazratmilad the problem is that you probably did not provide the SSL certificate of your Elastic instance.

You can run the Elastic image without the SSL certificate with the following options:

**xpack.security.enabled=false
discovery.type=single-node**


`docker run --name es01 --net elastic -p 9200:9200 -it -e "xpack.security.enabled=false" -e "discovery.type=single-node" -m 1GB docker.elastic.co/elasticsearch/elasticsearch:8.10.4`

Do this only in your local environment!

Alternatively you can add the certificate to the laravel-scout-elasticsearch config.
