### ISSUE TITLE
Search result pagination error in ElasticSearch 7 - engine getTotalCount returns array

### ISSUE THREAD

**Issue by Justas-S** [matchish/laravel-scout-elasticsearch#26]
Calling `Model::search('query')->paginate(10)` throws an exception:
> PHP Error:  Unsupported operand types in /home/vagrant/dev/maze/vendor/laravel/framework/src/Illuminate/Pagination/LengthAwarePaginator.php on line 51

This is caused by [ElasticSearchEngine->getTotalCount](https://github.com/matchish/laravel-scout-elasticsearch/blob/master/src/Engines/ElasticSearchEngine.php#L114) returning an array instead of an integer  value. It returns the `hits.total` value which is an array with `hits.total.value` and `hits.total.relation` keys as documented [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-search-API.html).

**Comment by matchish** [comment]
Thanks for the issue. I missed release of elasticsearch 7. I'll run tests in es 7 and then fix the issue

**Comment by matchish** [comment]
You can try `elasticsearch-7` branch https://github.com/matchish/laravel-scout-elasticsearch/tree/elasticsearch-7
Not it passes all tests, but I'm not going to merge the branch to master in the near feature, because official elasticsearch php package still not published. 
I don't have any project with elasticsearch 7 right now, so It will be great if you give some feedback
