### ISSUE TITLE
Difference between this package and others

### ISSUE THREAD

**Issue by mauxtin** [matchish/laravel-scout-elasticsearch#3]
Hi @matchish and thanks for open sourcing this package of yours! 😃 

Any chance you could write a few words on why you created a new package instead of using an existing one?

I have been using this package for a while https://github.com/babenkoivan/scout-elasticsearch-driver and since the original maintainer no longer supports it I was thinking of switching to something else.  The second reason was the big number of unsolved issues ( not sure if they are valid or not but they are there).

Anyway, would love to see how this differentiates from others.

Thanks again 😸

**Comment by matchish** [comment]
Hey @mauxtin thanks for your interest to the project)

I've started this project because I believe that scout engine should not introduce new methods to a builder and should be compatible with the original scout package. 

As you mentioned https://github.com/babenkoivan/scout-elasticsearch-driver abandoned and now if you want  to switch to another engine you need to rewrite a lot of code if your search is complex

This package doesn't introduce new DSL and uses stable package [ongr-io/ElasticsearchDSL](https://github.com/ongr-io/ElasticsearchDSL)

Also the package less verbose when you need reimport your models
`php artisan scout:import`
vs
`php artisan elastic:update-index App\\MyIndexConfigurator`
`php artisan elastic:migrate App\\MyModel my_index_v2`

This package [https://packagist.org/packages/tamayo/laravel-scout-elastic](https://packagist.org/packages/tamayo/laravel-scout-elastic) don't have import command at all

And I believe that this package has cleaner code and better tests

Next things I want to implement is progress bar for console commands and search by multiple models

**Comment by mauxtin** [comment]
Thanks @matchish! Will definitely give this a go soon 😺
