### ISSUE TITLE
scout:import

### ISSUE THREAD

**Issue by DivOverlow** [matchish/laravel-scout-elasticsearch#30]
php artisan scout:import
Importing [App\Model\frontend\post]

   Illuminate\Contracts\Container\BindingResolutionException  : Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport

What did I miss?

**Comment by matchish** [comment]
The error throws because of `\ElasticSearch\Client` isn't registered in a service provider

The package uses `\ElasticSearch\Client` from official package, but does not try to configure it, so feel free do it in your app service provider. But if you don't want to do it right now, you can use `Matchish\ElasticSearchServiceProvider` from the package.
Register the provider, adding to `config/app.php`
```

'providers' => [
    // Other Service Providers

    \Matchish\ScoutElasticSearch\ElasticSearchServiceProvider::class
],
```
