### ISSUE TITLE
Eager loading relationships

### ISSUE THREAD

**Issue by joelennon** [matchish/laravel-scout-elasticsearch#31]
First off, thank you for a fantastic package. We migrated from Algolia to ES about 6 months ago and at the time struggled with the other packages as none of them seemed to work perfectly for our use case. We ended up writing our own engine based on a combination of the other packages’ approaches and some of our own tweaks, but it’s never been great. What I love about this package is that it strikes the right balance of keeping the simplicity of the Scout API while still offering the ability to benefit from the power of ES.

So one of the problems we’ve historically had with Scout is with the performance of bulk importing records at scale (millions of records). For many of our searchable indexes, we need to load additional properties into the record from related models in the database, sometimes even from nested relations. Unfortunately Scout (and indeed this package) do not fare well in this scenario, creating N+1 queries that ultimately end up bringing the database to its knees when bulk importing.

I have a solution for the problem and have implemented it in a fork, but I wanted to check if this is something you’d likely accept a PR for. Essentially I add a method to the searchable models that require eager loaded relations, which returns an array of the relations to eager load. I’ve then changed the `PullFromSource` class of this package to check if the searchable model has this method, and if so, add a `with` to the query to eagerly load those relations.

https://github.com/workvivo/laravel-scout-elasticsearch/commit/c7d5f983dd87da773667ad0bcbb6aa0feb7c7689

If you think there is a better way to approach this problem I’d love to hear it - I suspect this is an issue for a lot of people who use Scout at scale. This is also an issue with the default Scout Algolia implementation (https://github.com/laravel/scout/issues/329) and they rejected a similar PR there (https://github.com/laravel/scout/pull/342). If you’re open to a PR on this feature, let me know and I’ll tidy up my fork and add some tests for the scenario before submitting a PR.

Thanks again for the fantastic package.

**Comment by matchish** [comment]
Hello) Thank you so much for your kind words and feedback!
I agree that import performance is crucial for elasticsearch engine, because if you need elasticsearch probably you have a lot of documents)
I've checked your PR but I think eager loading should be done outside of the package to not introduce new dependencies.
For example you can decorate your model and add global scope to it
```
<?php

namespace App;

use App\Scopes\BrandScope;
use Illuminate\Database\Eloquent\Model;

class ProductWithBrand extends Brand
{
    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new BrandScope);
    }
}
```
If you don't need brand in search results you can unregister the scope passing callback to `query` method. 
Now I don't like two things in the solution
1. We put `ProductWithBrand` instead of `Product` in a index
2. We need unregister scope if we don't need brand in a search results
But I think there is a solution to eager load relations from outside of the package, or maybe we should pass some factory to the import command and it will create `Product` model with added global scope for us.

Probably I'll add a solution for this case to README when I'll find a good one. So if you have any idea how to eager load relations not in the package I'll be glad to hear it!

**Comment by matchish** [comment]
@joelennon To be honest I think all this [code](https://github.com/workvivo/laravel-scout-elasticsearch/blob/c7d5f983dd87da773667ad0bcbb6aa0feb7c7689/src/Jobs/Stages/PullFromSource.php#L50) should outside of the package. Probably later I'll introduce an interface to decorate searchable model in the import command. Then the package will be less coupled with the searchable trait, and you can easy eager load relations when import to es.

**Comment by joelennon** [comment]
Thanks for the feedback @matchish - appreciate your efforts with the package.
